
[project]
name = "jpd"
description = "I'm just trying to get better at the PagerDuty API by building this little search tool... "
license = {text="GPL-2.0-only"}
dynamic = ["version"]
authors = [{name="Paul Miller", email="paul@merb.net" }]
maintainers = [{name="Paul Miller", email="paul@merb.net" }]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
dependencies = [
    "pagerduty",
    "tabulate",
    "dateparser",
    "simplejson",
    "xdg",
    "bs4",
]

[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "jpd/version.py"

[project.scripts]
jpd = "jpd.cmd:entry_point"

[project.urls]
Github = "https://github.com/jettero/jpd.git"

[tool.setuptools]
packages = ["jpd"]
